CREATE TABLE [dbo].[Relation_Article](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[NoArticle_PREF] [nvarchar](255) NULL,
	[NoArticle_NAV] [nvarchar](255) NULL,
PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
