
CREATE TABLE [dbo].[Stage_MaterielOptimization](
	[id] [int] NOT NULL,
	[NumeroOptimization] [int] NOT NULL,
	[Numero] [int] NOT NULL,
	[Version] [int] NOT NULL,
	[Ordre] [smallint] NOT NULL,
	[Sous-Modele] [int] NOT NULL,
	[Reference] [nchar](25) NOT NULL,
	[Config. Couleur] [int] NOT NULL,
	[Quantité par fenêtre] [int] NOT NULL,
	[Quantité] [int] NOT NULL,
	[Longueur] [numeric](19, 6) NOT NULL,
	[Hauteur] [numeric](19, 6) NOT NULL,
	[AngleCoupeA] [numeric](19, 6) NOT NULL,
	[AngleCoupeB] [numeric](19, 6) NOT NULL,
	[Complexe] [smallint] NOT NULL,
	[IdMateriel] [int] NOT NULL,
	[IdPeinture] [int] NOT NULL,
	[Angle] [smallint] NOT NULL,
	[Peinture] [smallint] NOT NULL,
	[Composite] [smallint] NOT NULL,
	[Composante] [smallint] NOT NULL,
	[NoVerre] [int] NOT NULL,
	[Demonte] [smallint] NOT NULL,
	[IdEtalonPeinture] [smallint] NOT NULL,
	[Lieu de travail] [smallint] NULL,
	[Ref. Original] [nvarchar](25) NULL,
	[Poid] [numeric](19, 6) NOT NULL,
	[Cote Modele] [smallint] NULL,
	[Date de creation] [datetime] NULL,
	[Date de Modif.] [datetime] NULL
) ON [PRIMARY]